global:
  scrape_interval: 5s
scrape_configs:
  - job_name: vehicle-platform-api
    static_configs:
      - targets: ["api:8000"]
  - job_name: vehicle-platform-stream-consumer
    static_configs:
      - targets: ["stream-consumer:8001"]
